
services:

  app-mysql:
    restart: on-failure
    build: artifacts
    ports:
      - "8080:8080"
    environment:
      - SPRING_CREDIT_GATE_URL=http://node-app:9999/payment
      - SPRING_PAYMENT_GATE_URL=http://node-app:9999/payment
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/app
      - SPRING_DATASOURCE_USERNAME=app
      - SPRING_DATASOURCE_PASSWORD=pass
      - SERVER_PORT=8080
    command: ["java", "-jar", "aqa-shop.jar"]
    depends_on:
      - mysql

  app-postgresql:
    build: artifacts
    ports:
      - "8081:8081"
    environment:
      - SPRING_CREDIT_GATE_URL=http://node-app:9999/payment
      - SPRING_PAYMENT_GATE_URL=http://node-app:9999/payment
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/app
      - SPRING_DATASOURCE_USERNAME=app
      - SPRING_DATASOURCE_PASSWORD=pass
      - SERVER_PORT=8081
    command: ["java", "-jar", "aqa-shop.jar"]
    depends_on:
      - postgresql

  mysql:
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./data-mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  postgresql:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./data-postgres:/var/lib/postgres
    environment:
       - POSTGRES_DB=app
       - POSTGRES_USER=app
       - POSTGRES_PASSWORD=pass

  node-app:
    build: node-app
    image: node-app:1.0
    ports:
       - '9999:9999'


